"""Add AI mode and Gemini settings to users

Revision ID: 8d065b5c7883
Revises: f64da4ca89d8
Create Date: 2026-09-16 12:53:11.975888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d065b5c7883'
down_revision = 'f64da4ca89d8'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('users', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('ai_mode', sa.String(length=20), nullable=False))
#         batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
#         batch_op.add_column(sa.Column('gemini_model_name', sa.String(length=100), nullable=True))
def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_mode', sa.String(length=20), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gemini_model_name', sa.String(length=100), nullable=True, server_default='gemini-2.0-flash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gemini_model_name')
        batch_op.drop_column('gemini_api_key')
        batch_op.drop_column('ai_mode')

    # ### end Alembic commands ###
