"""Make Feedback.user_id nullable, add guest_name and guest_email

Revision ID: f64da4ca89d8
Revises: eee90a96cf45
Create Date: 2026-08-01 11:41:49.836101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64da4ca89d8'
down_revision = 'eee90a96cf45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
